# Generated by Django 5.2.4 on 2026-04-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/default/default.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
