# Generated by Django 5.2.4 on 2025-08-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Product',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_id_f21274_idx',
            old_name='shop_shop_id_383b90_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_name_a2070e_idx',
            old_name='shop_shop_name_ff50b8_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_created_ef211c_idx',
            old_name='shop_shop_created_903692_idx',
        ),
    ]
